### ISSUE TITLE
Lack of space issue

### ISSUE THREAD

**Issue by glenrobson** [glenrobson/github_iiif#31]
```
Jul 12, 2022 7:17:50 PM sun.net.www.http.HttpClient logFinest
FINEST: KeepAlive stream used: https://api.github.com/repos/hadro/jwst/contents/images/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/info.json
Failed to create and upload tiles due to: org.eclipse.egit.github.core.client.RequestException: Invalid request.

For 'properties/sha', nil is not a string. (422)
org.eclipse.egit.github.core.client.RequestException: Invalid request.

For 'properties/sha', nil is not a string. (422)
	at org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:622)
	at org.eclipse.egit.github.core.client.GitHubClient.sendJson(GitHubClient.java:713)
	at org.eclipse.egit.github.core.client.GitHubClient.put(GitHubClient.java:848)
	at com.gdmrdigital.iiif.model.github.ExtendedContentService.setContents(ExtendedContentService.java:49)
	at com.gdmrdigital.iiif.model.github.ExtendedContentService.setContents(ExtendedContentService.java:25)
	at com.gdmrdigital.iiif.controllers.Repo.uploadDirectory(Repo.java:441)
	at com.gdmrdigital.iiif.processor.ImageProcessor.run(ImageProcessor.java:66)
```

and
```
FINEST: KeepAlive stream used: https://api.github.com/repos/hadro/jwst/contents/images/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/info.json
Jul 12, 2022 7:16:20 PM sun.net.www.protocol.http.HttpURLConnection getInputStream0
Failed to create and upload tiles due to: org.eclipse.egit.github.core.client.RequestException: Invalid request.

For 'properties/sha', nil is not a string. (422)
org.eclipse.egit.github.core.client.RequestException: Invalid request.

For 'properties/sha', nil is not a string. (422)
	at org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:622)
	at org.eclipse.egit.github.core.client.GitHubClient.sendJson(GitHubClient.java:713)
	at org.eclipse.egit.github.core.client.GitHubClient.put(GitHubClient.java:848)
	at com.gdmrdigital.iiif.model.github.ExtendedContentService.setContents(ExtendedContentService.java:49)
	at com.gdmrdigital.iiif.model.github.ExtendedContentService.setContents(ExtendedContentService.java:25)
	at com.gdmrdigital.iiif.controllers.Repo.uploadDirectory(Repo.java:441)
	at com.gdmrdigital.iiif.processor.ImageProcessor.run(ImageProcessor.java:66)
```

and
```
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./0,0,7700,7382/241,231/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./0,0,7700,7382/482,462/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./0,0,7700,7382/963,923/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./0,0,4096,4096/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./0,4096,4096,3286/1024,822/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./4096,0,3604,4096/901,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./4096,4096,3604,3286/901,822/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./0,0,2048,2048/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./0,2048,2048,2048/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./0,4096,2048,2048/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./0,6144,2048,1238/1024,619/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./2048,0,2048,2048/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./2048,2048,2048,2048/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./2048,4096,2048,2048/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./2048,6144,2048,1238/1024,619/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./4096,0,2048,2048/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./4096,2048,2048,2048/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./4096,4096,2048,2048/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./4096,6144,2048,1238/1024,619/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./6144,0,1556,2048/778,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./6144,2048,1556,2048/778,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./6144,4096,1556,2048/778,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./6144,6144,1556,1238/778,619/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./0,0,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./0,1024,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./0,2048,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./0,3072,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./0,4096,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./0,5120,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./0,6144,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./0,7168,1024,214/1024,214/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./1024,0,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./1024,1024,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./1024,2048,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./1024,3072,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./1024,4096,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./1024,5120,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./1024,6144,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./1024,7168,1024,214/1024,214/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./2048,0,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./2048,1024,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./2048,2048,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./2048,3072,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./2048,4096,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./2048,5120,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./2048,6144,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./2048,7168,1024,214/1024,214/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./3072,0,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./3072,1024,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./3072,2048,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./3072,3072,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./3072,4096,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./3072,5120,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./3072,6144,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./3072,7168,1024,214/1024,214/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./4096,0,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./4096,1024,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./4096,2048,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./4096,3072,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./4096,4096,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./4096,5120,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./4096,6144,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./4096,7168,1024,214/1024,214/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./5120,0,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./5120,1024,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./5120,2048,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./5120,3072,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./5120,4096,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./5120,5120,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./5120,6144,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./5120,7168,1024,214/1024,214/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./6144,0,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./6144,1024,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./6144,2048,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./6144,3072,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./6144,4096,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./6144,5120,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./6144,6144,1024,1024/1024,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./6144,7168,1024,214/1024,214/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./7168,0,532,1024/532,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./7168,1024,532,1024/532,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./7168,2048,532,1024/532,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./7168,3072,532,1024/532,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./7168,4096,532,1024/532,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./7168,5120,532,1024/532,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./7168,6144,532,1024/532,1024/0/default.jpg
Failed to write /mnt/storage/031bd3e9-7e71-4687-bb73-f71923df3dbe/tiles/Stephans_Quintet_NIRCam_and_MIRI_Composite_Image/./7168,7168,532,214/532,214/0/default.jpg
```

Disk space:

```
/dev/xvdf       9.8G  8.7G  598M  94% /mnt/storage
```

**Comment by glenrobson** [comment]
Moved to creating images using github actions
